<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <RootNamespace>LucentMist.Web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LucentMist.Agent\LucentMist.Agent.csproj" />
    <ProjectReference Include="..\LucentMist.Scanning\LucentMist.Scanning.csproj" />
    <ProjectReference Include="..\LucentMist.Tools\LucentMist.Tools.csproj" />
    <ProjectReference Include="..\LucentMist.Core\LucentMist.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
  </ItemGroup>

</Project>
