<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LucentMist.Tools\LucentMist.Tools.csproj" />
    <ProjectReference Include="..\..\src\LucentMist.Core\LucentMist.Core.csproj" />
    <ProjectReference Include="..\..\src\LucentMist.CLI\LucentMist.CLI.csproj" />
    <ProjectReference Include="../LucentMist.CLI.TestHost/LucentMist.CLI.TestHost.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
