<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>LucentMist.CLI</RootNamespace>
    <AssemblyName>lmist</AssemblyName>
    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LucentMist.Tools.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LucentMist.Agent\LucentMist.Agent.csproj" />
    <ProjectReference Include="..\LucentMist.Scanning\LucentMist.Scanning.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Spectre.Console" />
  </ItemGroup>

</Project>
